app/__init__.py
from flask import Flask
from authlib.integrations.flask_client import OAuth
import json
from werkzeug.middleware.proxy_fix import ProxyFix

app = Flask(__name__)
app.wsgi_app = ProxyFix(app.wsgi_app, x_proto=1) # trust the X-Forwarded-Proto header set: http or https

with open('app/client_secrets.json') as f:
    secrets = json.load(f)
    app.secret_key = secrets['secret_key']
    kc_client_id = secrets['kc_client_id']
    kc_client_secret = secrets['kc_client_secret']

oauth = OAuth(app)

# import and register routes
from app.main.routes import main_bp
from app.keycloak.routes import kc_bp

app.register_blueprint(main_bp)
app.register_blueprint(kc_bp)

app/keycloak/routes.py
from flask import Blueprint, url_for, session, redirect
from app import oauth, kc_client_id, kc_client_secret

kc_bp = Blueprint('kc', __name__)

kc = oauth.register(
    name = 'kc',
    client_id = kc_client_id,
    client_secret = kc_client_secret,
    server_metadata_url='https://xxxx.com/auth/realms/realmname/.well-known/openid-configuration',
    client_kwargs = {'scope': 'openid'},
)

# OpenID Connect Authorization Code Flow
@kc_bp.route('/login/kc')
def kc_login():
    redirect_uri = url_for('.kc_authorize', _external=True)
    # redirect to Keycloak server
    return kc.authorize_redirect(redirect_uri)

@kc_bp.route('/authorize/kc')
def kc_authorize():
    token = kc.authorize_access_token()
    # get the roles info from the ID token
    session['login'] = {
        'name': token.get('userinfo').get('name'),
        'roles': token.get('userinfo').get('roles')
    }
    return redirect('/')


@kc_bp.route('/logout')
def logout():
    # clear the session data and logout the user from Keycloak
    session.clear()
    return redirect('https://xxxx.com/auth/realms/realmname/protocol/openid-connect/logout?redirect_uri=xxxx.com/')

app/main/routes.py
from flask import Blueprint, render_template, session, flash, send_from_directory, url_for, abort
import os
from app import app

main_bp = Blueprint('main', __name__)

@main_bp.route('/')
def homepage():
    # if logged in, display the correct image depending on the user's role
    if 'login' in session:
        try:
            roles = session['login']['roles']
            if 'admin-user' in roles:
                image = url_for('main.protected', filename='admin.png')
            elif 'special-user' in roles:
                image = url_for('main.protected', filename='special.jpeg')
            elif 'common-user' in roles:
                image = url_for('main.protected', filename='user.png')
        except TypeError: # when user has no roles, roles is NoneType and as such non iterable
            flash('You logged in successfully but have no roles, contact admin.', 'error')
    else:
        # if not logged in, return default welcome image
        image = url_for('static', filename='welcome.jpeg')

    return render_template("base.html", image=image)


@main_bp.route('/protected/<path:filename>')
def protected(filename):
    # return protected image only if logged in
    if 'login' in session:
        return send_from_directory(
            os.path.join(app.root_path, 'protected'), filename)
    else:
        abort(404)

app/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="">SOASec Project</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          {% if 'login' in session %}
          <a class="nav-item nav-link" id="name">{{session.get('login').get('name')}}</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else%}
          <a class="nav-item nav-link" id="login"  href="{{url_for('kc.kc_login', _external=True)}}">Login</a>
          {% endif %}
        </div>
      </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}
    <div class="text-center">
      <p></p>
      <p></p>
      <img src="{{ image }}" class="img-fluid">
    </div>
    
    
    

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>